# Site settings
title:          zuneho.github.io
description:    "zuneho.github.io"
baseurl:        "/tale"
url:            "https://zuneho.github.io"

# Author
author:
  name:         Juneho Jung
  url:          https://zuneho.github.io
  email:        zuneho@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
